### ISSUE TITLE
commenter stops at video where comments are diabled

### ISSUE THREAD

**Issue by medienoekonom** [doppelgunner/YouBot#2]
Hey there, 

nice work. works fine... except: 
the bot stops working when he reaches a video where comments are diabled. 
then i cannot see which videos where already commented so i have to click through all videos and search for my comment. thats a lot of work :) 
![image](https://user-images.githubusercontent.com/20904559/28709563-211120ca-7381-11e7-816c-7086af0ec333.png)

Suggestion: filter videos with comments disabled (but i have no clue if there is such an option by the api).
suggestion: just tick of which videos where successfull comment was posted.

**Comment by doppelgunner** [comment]
Ok thanks ill try to fix it some other time when im not busy.

**Comment by doppelgunner** [comment]
Is it ok to notify the user of how many videos have disabled comments then just delete them from selected list?

**Comment by doppelgunner** [comment]
done! I just notify the user of how many videos in the list have comments disabled then remove it on the list afterwards.

Ill upload it after im done adding theme lol. bonus feature I guess?

**Comment by medienoekonom** [comment]
you are just awesome. cant wait to try the new version :) 
theming is always nice! thx. 
lets find out how many videos i can comment with this. 🥇

**Comment by doppelgunner** [comment]
I'll add the option to add theme by editing the data/theme/style.css but it will have no style as default cause it just saves me trouble. But, by adding the css anyone can have their custom theme by adding a little bit of css.

**Comment by doppelgunner** [comment]
Fixed w/ [v1.0.1.6](https://github.com/doppelgunner/YouBot/releases/tag/v1.0.1.6)
See commit: df9610892ee289fdbf612ca48613151605f6230c
